# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
   name = "STL",
   hdrs = [
      "set.hpp",
      "map.hpp"
   ],
   visibility = [
      "//visibility:public"
   ],
   strip_include_prefix = "",
)