# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_test(
   name = "set_test",
   srcs = ["set_test.cpp"],
   deps = [
      "//src/lib:STL",
      "@gtest//:gtest",
      "@gtest//:gtest_main"
   ],
)
